"""DLC_Character_STAR_V1.0.0 的文字总表（lang）：本包面向玩家的文字都住这里，别处只引用。

包自己的模块这样取：`TEXT = pack_text_from_file(__file__)`（见 `weiren_game/data/lang.py`）。
模板写法与 base 相同：`{名字}` + 调用处 `.format(名字=…)`。
"""

from __future__ import annotations

TEXT: dict[str, str] = {

    # ---------------------------------------------------------------- dlc
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.NAME_FIRE": "压制射击",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.NAME_FIRE_DESC": "处理门外当前的事件：人类访客被惊退；伪人到访则清除该事件，并令其 {p1} 回合内不再来访。发动时放空全部【{p2}】电量；仅在电量充满（{p3}/{p4}）时可发动，放空后必然进入低功耗。*该能力有 {p5} 回合冷却时间。",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.NAME_GUN": "流星信标",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.NAME_MARK": "复合生化电池",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.NAME_PASSIVE_COVER": "掩护射击",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.NAME_PASSIVE_COVER_DESC": "STAR 在屋内且持有【{p1}】时，可开启【{p2}】为在外搜索的同伴提供火力掩护：同伴受到伪人主动能力影响时，有 {p3:.0%} 概率免疫该影响。未开启时不提供任何掩护。",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.NAME_PASSIVE_ENERGY": "半永久能源动力炉",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.NAME_PASSIVE_ENERGY_DESC": "STAR 搭载【{p1}】，上限 {p2} 点；每回合开始时充能 {p3} 点，若生命值为上限则额外充能 {p4} 点。每回合结束时扣除 {p5} 点供能，使当回合的理智消耗量与高生命值自然流失量各-{p6:.0%}。若电量不足 {p7} 点则无法供能，进入低功耗：当回合的理智消耗量与生命流失量各+{p8}。",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.NAME_STATUS_COVER": "掩护射击",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.NAME_TOGGLE_COVER": "掩护射击",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.NAME_TOGGLE_COVER_DESC": "开启后：为在外搜索的同伴提供火力掩护——同伴受到伪人主动能力影响时有 {p1:.0%} 概率免疫该影响；每次实际抵御消耗 {p2} 点【{p3}】（每回合至多 {p4} 点）。关闭后：不提供掩护，也不消耗电量。",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR._apathy_modifiers.1": "角色被动",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR._cover_fire_modifier.1": "角色技能",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR._cover_fire_modifier.2": "{p1}为外出的同伴提供掩护射击。",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR._health_loss_modifier.1": "角色被动",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR._health_loss_modifier.2": "生命流失",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR._health_loss_modifier.3": "高生命值自然流失",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR._resolve_door.1": "{p1}朝天放了一枪，门外的人退开了。",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR._resolve_door.2": "{p1}{p2}，门外的东西暂时退去了。",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR._sanity_consume_modifier.1": "角色被动",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.detail_slot.1": "每次实际抵御消耗 {p1} 电量，抵御 {p2:.0%}",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.detail_slot.2": "每回合 +{p1}",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.detail_slot.3": "（动力炉状态良好 +{p1}）",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.detail_slot.4": " · **低功耗**：回合末消耗 +{p1}",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.detail_slot.5": " · 供能中：回合末扣 {p1}，自然消耗降至 {p2:.0%}",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.detail_slot.6": "状态",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.end_turn_settle.1": "{p1}消耗 {p2} 点{p3}，回合末的自然消耗减轻了。",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.end_turn_settle.2": "{p1}的{p2}已经见底，{p3}进入低功耗状态。",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.module.1": "有机计算机稳定化方案",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.module.10": "低于此处即低功耗",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.module.11": "它知道自己还剩多少电。低于一格时，身体会替它硬撑。",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.module.12": "STAR把枪口对着门外，不是为了打中谁；是为了让外面知道这里有枪。",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.module.2": "STAR 受到的理智伤害-{p1:.0%}；消沉值变化量、理智回复量与觉醒情绪获取量均×{p2:.0%}。",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.module.3": "特殊作战部队Freesia的指挥官直属通用型特殊支援单元，感情平淡但意外的喜欢交流。喜欢吃松饼。",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.module.4": "改造人",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.module.5": "18-24岁",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.module.6": "未知的性别",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.module.7": "星星",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.module.8": "冷却 {p1} 回合",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.module.9": "每回合开始时充能 {p1} 点；若生命值为上限则额外充能 {p2} 点，上限 {p3} 点。每回合结束时扣除 {p4} 点供能，抵消当回合的部分自然消耗。",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.requirements_fire.1": "需要{p1}才能开火。",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.requirements_fire.2": "门外没有值得开枪的目标。",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.requirements_fire.3": "{p1}没有充满（{p2}/{p3}），无法开火。",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.requirements_fire.4": "本次对局至多开火 {p1} 次。",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.turn_start.1": "{p1}的{p2}已经充能完毕（{p3}/{p4}）。",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.turn_start.2": "，动力炉状态良好 +{p1}",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.turn_start.3": "{p1}的{p2}充能 {p3} 点（{p4}/{p5} → {p6}/{p7}{p8}）。",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.use_fire.1": "把 {p1} 点{p2}一次放空",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.use_toggle.1": "{p1}关闭了{p2}。",
    "dlc.DLC_Character_STAR_V1.0.0.characters.STAR.use_toggle.2": "{p1}开启了{p2}。",
    "dlc.DLC_Character_STAR_V1.0.0.items.sidearm.FLAVOR": "STAR专用手枪型能量武器，通过自身供能无需弹药同时共享传感器数据；如同身体的延伸。\n“流星信标，校准完毕。交给本人吧。”",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR.CODEX_SKILLS.0.0": "突破 · {p1}",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR.CODEX_SKILLS.0.1": "漏洞体来访时，若屋内任一房客的焦虑强度 ≥ {p1}，则触发突破。",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR.CODEX_SKILLS.1.0": "解放 · {p1}",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR.CODEX_SKILLS.1.1": "连续 {p1} 次到访期间，屋内最高焦虑强度需依次低于 {p2} / {p3} / {p4}（要求逐次收紧）；期间最高焦虑强度 ≥ {p5} 则进度清零，从下一次到访重新计算。",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR.CODEX_SKILLS.2.0": "主动能力① · {p1}",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR.CODEX_SKILLS.2.1": "漏洞体到访时，若屋内最高焦虑强度 ≥ {p1}，立刻对最高焦虑的房客发动：令其焦虑强度 +{p2}，并令接下来 {p3} 回合内没有访客来访。该效果只封锁人类访客，对漏洞体自身无效。",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR.CODEX_SKILLS.3.0": "被动能力① · {p1}",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR.CODEX_SKILLS.3.1": "漏洞体每次到访时，取屋内焦虑强度最低的 {p1} 名房客，令其焦虑强度 +{p2}、层数 +{p3}。该效果不经过抵御判定。",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR.CODEX_SKILLS.4.0": "被动能力② · {p1}",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR.CODEX_SKILLS.4.1": "对局开始后，所有房客搜索时遭遇漏洞体的概率为 {p1:.0%} + {p2:.0%} × 漏洞体到访次数。遭遇时令该房客焦虑强度 +{p3}、层数 +{p4}，并有 {p5:.0%} 概率令其丢失 1 件携带物资。",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR.MARK_LABEL": "异常堆栈-漏洞体",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR.NAME_BREAKTHROUGH": "任意代码执行",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR.NAME_LIBERATION": "强制回滚",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR.NAME_PSEUDO": "无法收敛的漏洞体-STAR",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR.NAME_SEARCH": "上下文泄漏",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR.NAME_SHOT": "恐吓射击",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR.NAME_VISIT": "提示词污染",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR._apply_visit_anxiety.1": "{p1}的焦虑被推高（+{p2}/+{p3}）。",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR._maybe_shoot.1": "门外传来一声枪响；{p1}的焦虑骤然升高（+{p2}），一时不会有人敢来敲门。",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR.attack_searcher.1": "，并震落了携带的物资",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR.attack_searcher.2": "伪人袭击：{p1}在暗处听见一声枪响，心神不宁（焦虑 +{p2}）{p3}。",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR.card_info.1": "{p1}：连续达标 {p2}/{p3}（安全线 {p4}）",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR.card_info.2": "{p1}：焦虑峰值 {p2}/{p3}（已到访 {p4} 次）",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR.card_info.3": "到访时峰值 ≥{p1} 即发动：该房客焦虑 +{p2}，且 {p3} 回合内无访客来访。",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR.card_info.4": "焦虑峰值",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR.card_info.5": "每次到访令 {p1} 名焦虑最低的房客 焦虑 +{p2}/+{p3}。",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR.card_info.6": "搜索遭遇率 {p1:.0%} + {p2:.0%} × 到访次数；遭遇者焦虑 +{p3}/+{p4}，并有 {p5:.0%} 概率丢失 1 件携带物资。",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR.progress_text.1": "焦虑峰值{p1}，解放进度{p2}/{p3}（安全线{p4}）",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR.visit.1": "屋内焦虑失控（峰值 {p1}/{p2}），伪人完成突破。",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR.visit.2": "焦虑峰值 {p1} 越过中断线 {p2}，解放进度重置。",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR.visit.3": "峰值 {p1} 低于安全线 {p2}，解放进度 {p3}/{p4}。",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR.visit.4": "焦虑始终没有失控，伪人的漏洞被彻底摸清；它归于平静，得到解放。",
    "dlc.DLC_Character_STAR_V1.0.0.pseudos.pseudo_STAR.visit.5": "峰值 {p1} 未达安全线 {p2}，本次到访不推进解放进度。",

    # ---------------------------------------------------------------- item
    "item.star_sidearm.description": "STAR 的个人佩枪，满足特定能力的发动条件。",
    "item.star_sidearm.name": "流星信标",

    # ---------------------------------------------------------------- pseudo
    "pseudo.pseudo_STAR.breakthrough": "来访时屋内最高焦虑强度≥{p1}。",
    "pseudo.pseudo_STAR.description": "轮廓比常人更整齐，动作没有多余的停顿，开口的间隔像被校准过。",
    "pseudo.pseudo_STAR.liberation": "连续{p1}次到访，最高焦虑强度依次低于{p2}/{p3}/{p4}；期间最高焦虑强度≥{p5}则进度重置。",
}
