"""给内容模块做类型标注用的运行期接口协议。

角色档案（``data/characters/*.py``）目前以 ``EngineProtocol`` 代替裸
``object`` 标注引擎参数，避免内容包与引擎之间的循环导入。该协议只用于
标注与 IDE 提示，运行期不做结构检查。
"""

from __future__ import annotations

from typing import Any, Protocol
from weiren_game.data.lang import TEXT


class EngineProtocol(Protocol):
    """角色模块可见的引擎接口：**方法列表即内容层实际会调用的引擎 API**
    （由 `tools/dump_core.py --refs` 实测得出；`tests/` 与 `tools/` 的引用不算）。

    仅用于标注与 IDE 提示，运行期不做结构检查。**加内容若要调引擎的新方法，
    先把它补进这里**——这份清单就是"内容能碰什么"的权威。
    """

    state: Any

    # ---- engine ----
    def home_tenants(self) -> list[TenantState]: ...
    def _log(self, message: str, *, shown: bool=True, detail: dict | None=None, kind: str='') -> None: ...
    def character(self, tenant: TenantState | str) -> CharacterDefinition: ...
    def _require_home_tenant(self, tenant_id: int | None, *, must_act: bool=False) -> TenantState: ...
    def _finish(self, victory: bool, ending: str) -> None: ...
    def _collect_flush(self, summary: str='', *, title: str='', detail: dict | None=None, rows: list[dict] | None=None) -> None: ...
    def _collect_start(self) -> None: ...
    def defer_search_report(self, mission, text: str) -> None: ...
    def emotion_visible(self, tenant: object, key: str) -> bool: ...
    def _clear_pending_choice(self) -> None: ...
    def _record_action(self, action: str, **data: Any) -> None: ...
    def _kill_tenant(self, tenant: TenantState, reason: str) -> None: ...
    def container(self, tenant: TenantState, key: str) -> object | None: ...
    def living_tenants(self) -> list[TenantState]: ...

    # ---- personality_system ----
    def _passive_available(self, tenant: Tenant, event_id: str='passive') -> bool: ...
    def _is_personality(self, tenant: Tenant, personality: str) -> bool: ...
    def _bond_tier(self, personality: str, level: int | None=None) -> int: ...
    def bond_levels(self) -> dict[str, int]: ...

    # ---- random_system ----
    def _rng(self, event_id: str | int, *suffix: object) -> random.Random: ...
    def discover(self, pool: Sequence[Any], *, count: int=3, constraint: Callable[[Any], bool] | None=None, required: Sequence[Any] | None=None, event_id: str | None=None, event_suffix: Sequence[object]=()) -> list[Any]: ...

    # ---- value_system ----
    def _restore_sanity(self, tenant: Tenant, amount: float, source: str=TEXT['systems.value_system._restore_sanity.1']) -> float: ...
    def _restore_health(self, tenant: Tenant, amount: float, source: str=TEXT['systems.value_system._restore_health.1']) -> float: ...
    def _consume_sanity(self, tenant: Tenant, amount: float, source: str) -> float: ...
    def _damage_health(self, tenant: Tenant, amount: float, source: str) -> float: ...
    def _consume_held_durability(self, tenant: Tenant, held: ItemInstance, amount: int) -> bool: ...
    def _loss_health(self, tenant: Tenant, amount: float, source: str) -> float: ...
    def _after_health_changed(self) -> None: ...
    def _loss_sanity(self, tenant: Tenant, amount: float, source: str) -> float: ...
    def _consume_health(self, tenant: Tenant, amount: float, source: str) -> float: ...
    def _damage_sanity(self, tenant: Tenant, amount: float, source: str) -> float: ...

    # ---- ability_system ----
    def _skill_outcome(self, actor: object, skill_id: str, success: bool) -> None: ...
    def _set_ability_cooldown(self, tenant: Tenant, ability_id: str, until: int) -> None: ...
    def _expel_tenant(self, tenant: Tenant, source: str, *, sanity_exempt_ids: set[str] | None=None) -> None: ...
    def _local_skill_module(self, character_id: str): ...
    def use_ability(self, actor_id: str, target_id: str | None=None, ability_id: str | None=None, option: str | None=None, amount: int | None=None, copied_ability_id: str | None=None, secondary_target_id: str | None=None, secondary_option: str | None=None, secondary_amount: int | None=None, force_max_amount: bool=False, forced: bool=False, _bypass_limits: bool=False) -> Any: ...

    # ---- marks_system ----
    def _set_global_event(self, event_id: str, value: float=0.0, layers: int=1) -> None: ...
    def _mark_count(self, tenant: object, mark_id: str) -> float: ...
    def _gain_mark(self, tenant: object, mark_id: str, amount: float=1.0, *, external: bool=False): ...
    def _has_persona(self, tenant: object, persona: str) -> bool: ...
    def _consume_mark(self, tenant: object, mark_id: str, amount: float=1.0, *, external: bool=False) -> float: ...
    def _global_event_value(self, event_id: str, default: float=0.0) -> float: ...
    def _consume_global_event(self, event_id: str) -> object: ...
    def _emit_node(self, node: str, **context: object) -> None: ...
    def _suppress_pseudo(self, layers: int, capabilities: object=None) -> None: ...
    def _global_event_active(self, event_id: str) -> bool: ...
    def _personas_of(self, tenant: object) -> list[str]: ...
    def _pseudo_capability(self, name: str) -> bool: ...
    def _pseudo_enters_house(self) -> bool: ...
    def _set_personas(self, tenant: object, values: list[str]) -> None: ...

    # ---- condition_system ----
    def _reduce_emotion_set(self, tenant: Tenant, group: str, intensity: int, layers: int, maximum_intensity: int=10) -> None: ...
    def _recover_condition(condition: Condition, layers: int, intensity: int) -> None: ...
    def _adjust_emotion_set(self, tenant: Tenant, group: str, intensity: int, layers: int, source: str) -> None: ...
    def _extend_condition(self, tenant: Tenant, condition: Condition, times: int, source: str) -> int: ...
    def _strengthen_emotion_set(self, tenant: Tenant, group: str, intensity: int, layers: int, source: str) -> None: ...
    def _worsen_condition(self, tenant: Tenant, condition: Condition, times: int, source: str) -> int: ...
    def _apply_emotion(self, tenant: Tenant, key: str, intensity: int, layers: int, source: str, *, scale_awakening: bool=True) -> bool: ...
    def _strengthen_named_emotion(self, tenant: Tenant, key: str, intensity: int, layers: int, source: str) -> bool: ...
    def _add_condition(self, tenant: Tenant, condition: Condition, intensity: int, layers: int, source: str) -> bool: ...
    def _set_condition(self, tenant: Tenant, condition: Condition, intensity: int, layers: int, source: str) -> bool: ...

    # ---- information_system ----
    def _observe_pseudo_skill(self, skill_id: str) -> None: ...
    def _create_random_information(self, verified: bool, source: str, allowed_kinds: set[str] | None=None) -> Information: ...
    def _verify_information_object(self, info: Information) -> None: ...
    def _discern_one_information(self, tenant: Tenant, *, false_only: bool=False) -> bool: ...

    # ---- pseudo_system ----
    def _pseudo_actions_suppressed(self) -> bool: ...
    def _skill_respond_skill(self, skill: str, stage: str, *, mode: str, caster: object, target: Tenant | None=None, mission: SearchMission | None=None, event: str | None=None, penalty: float | None=None) -> bool: ...
    def _attempt_breakthrough(self, reason: str) -> bool: ...
    def _break_search_tool(self, mission: SearchMission, tenant: Tenant, item_id: str) -> None: ...
    def _pseudo_handler(self, name: str): ...
    def pseudo_in_house(self) -> bool: ...
    def _set_pseudo_marks(self, target: float) -> bool: ...

    # ---- search_system ----
    def _random_item(self, *, required_tags: Sequence[str]=(), minimum_quality: int=0, fortune: float=0.0, event_id: str='item.any', event_suffix: Sequence[object]=()) -> str: ...
    def _recalculate_search(self, mission: SearchMission) -> None: ...

    # ---- item_system ----
    def _fragile_chance(self, base: float, tenant: Tenant | None=None) -> float: ...
    def _gain_item(self, item_id: str, amount: int=1, *, process_carrier: bool=True) -> None: ...
    def _spend_item_use(self, item_id: str, item: ItemDefinition, tenant: Tenant | None=None, cost: int | None=None, *, inventory=None, spot=None) -> None: ...
    def _take_item(self, item_id: str, inventory=None, *, spot=None) -> int: ...
    def _merge_house_item(self, item_id: str, amount: int, durability: int=0) -> None: ...
    def _tenant_item_ids(self, tenant: Tenant) -> list[str]: ...

    # ---- cost_system ----
    def _pay_ability_costs(self, payer: object, costs: list[object], *, target: object | None=None, forced: bool=False, include_optional: bool=False) -> None: ...

    # ---- visitor_system ----
    def _queue_human_visitor(self, reason: str | None=None, *, force_supply: bool=False) -> None: ...

    # ---- round_effects ----
    def _grant_learned_passive(self, tenant: Tenant, ability_id: str) -> None: ...


__all__ = ["EngineProtocol"]
