"""给内容模块做类型标注用的运行期接口协议。

角色档案（``data/characters/*.py``）目前以 ``EngineProtocol`` 代替裸
``object`` 标注引擎参数，避免内容包与引擎之间的循环导入。该协议只用于
标注与 IDE 提示，运行期不做结构检查。
"""

from __future__ import annotations

from typing import Any, Protocol


class EngineProtocol(Protocol):
    """角色模块可见的最小引擎接口（方法列表即各角色模块会调用的引擎 API，
    仅用于标注与 IDE 提示，运行期不做结构检查）。"""

    state: Any

    def _log(self, message: str, *, shown: bool = True) -> None: ...
    def _record_log(self, message: str) -> None: ...
    def _show_message(self, message: str) -> None: ...
    def _rng(self, event_id: object): ...
    def _passive_available(self, tenant: object, event_id: str = "passive") -> bool: ...
    def home_tenants(self): ...
    def living_tenants(self): ...
    def character(self, tenant: object): ...
    def _require_home_tenant(self, tenant_id: int | None, *, must_act: bool = False): ...

    def _restore_health(self, tenant: object, amount: float, source: str = "回复"): ...
    def _loss_health(self, tenant: object, amount: float, source: str): ...
    def _consume_health(self, tenant: object, amount: float, source: str): ...
    def _damage_health(self, tenant: object, amount: float, source: str): ...
    def _restore_sanity(self, tenant: object, amount: float, source: str = "回复"): ...
    def _consume_sanity(self, tenant: object, amount: float, source: str): ...
    def _damage_sanity(self, tenant: object, amount: float, source: str): ...
    def _loss_sanity(self, tenant: object, amount: float, source: str): ...
    def _recover_condition(self, condition: object, layers: int, intensity: int) -> None: ...
    def _verify_information_object(self, info: object) -> None: ...
    def _create_random_information(self, truth: bool, source: str, kinds: object): ...
    def _gain_item(self, item_id: str, amount: int = 1, *, process_carrier: bool = True) -> None: ...
    def _set_ability_cooldown(self, tenant: object, ability_id: str, until: int) -> None: ...
    def _mark_ability_used(self, tenant: object, ability_id: str) -> None: ...
    def _queue_human_visitor(self, text: str, *, force_supply: bool = False) -> None: ...


__all__ = ["EngineProtocol"]
